### PR TITLE
Alternate rewrite of LoFi Echo

### PR DESCRIPTION
**Pull request by djphazer**
I noticed what you were working on and kinda ran away with the idea, so I thought I'd share my implementation. All that 8-bit offset conversion math had my head spinning, so I just changed it to a signed 16-bit int buffer instead to keep it simple. This doubled the buffer size, so you might have to adjust that to make it play nice. Maybe I'll switch back to 8-bit, idk. Seems like the Proportion() function should make it simple.

I actually love how this sounds! Output B plays the buffer in reverse... fun to listen to A and B as a stereo pair.

Cheers

### CODE REVIEW

**Comment by armandvedel** [comment]
Ah cool  I'll have a look at your version. It had my head spinning too trying to keep it the way it was in the original loop recorder.

**Comment by armandvedel** [comment]
Thanks I like the idea of combining this with Dr. Crusher but I don't want to double the buffer size because the precious dynamic memory is needed for other apps. Any idea if there are any other apps that can be trimmed for memory?

**Comment by djphazer** [comment]
I've disabled the MIDI apps and a bunch of other ones I'm just not using to make the binary fit. If you need more runtime memory, just try setting the buffer size to something like 1024 instead. I think I might still switch it back to an 8-bit buffer though...

**Comment by armandvedel** [comment]
👍 LMK if you switch back to the 8 bit buffer

**Comment by djphazer** [comment]
Will do. I'll push another commit to this branch when I update it.

I had another idea tho, that might help you out - if there are multiple applets that need a large buffer for audio data, perhaps they could share a global one? or two - one for each hemisphere. Something I might try to implement.

**Comment by armandvedel** [comment]
yeah that sounds cool

**Pull request merged**
